apiVersion: v1
kind: Service
metadata:
  name: paytmdev-coll-b595d18362e04e16a8e3b1dc85f80c0d-srv
spec:
  selector:
    app: paytmdev-coll-b595d18362e04e16a8e3b1dc85f80c0d
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9064
  type: ClusterIP